# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    authentication_admin_handler:
        class: AppBackendBundle\Handler\AuthenticationHandler
        public: false
        arguments:  ['@router', '@service_container']
    
    logout_admin_handler:
        class: AppBackendBundle\Handler\LogoutHandler
        arguments:  ['@router'] 
