fos_user: 
    service:
        mailer: wrep.fosuserbundlemandrillmailer
    registration:
        confirmation:
            enabled: true
    db_driver: orm
    firewall_name: main
    user_class: AppModelBundle\Entity\User
    group:
        group_class: AppModelBundle\Entity\Group