<?php

namespace AppModelBundle\Entity;

/**
 * DataInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataInvitationRepository extends \Doctrine\ORM\EntityRepository
{
}
