parameters:
#    app_model.example.class: AppModelBundle\Example

services:
#    app_model.example:
#        class: %app_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
