app_frontend_game_index:
    path:     /
    defaults: { _controller: AppFrontendBundle:Game:index } 
    
app_frontend_game_tesure:
    path:     /tesure
    defaults: { _controller: AppFrontendBundle:Game:tesure } 